name: Create issue on commit

on: [ push ]

jobs:
  create_commit:
    runs-on: ubuntu-latest 
    permissions:
      issues: write 
    steps:
      - name: Create issue using REST API
        run: |
          curl \
          -X POST \
          -H "Accept: application/vnd.github.v3+json" \
          -H "content-type: application/json" \
          -H "authorization: Bearer ${{ secrets.ACCESS_TOKEN }}" \
          https://api.github.com/repos/${{ github.repository }}/issues \
          -d '{"title": "issue for commit: ${{ github.sha }}","body": "This issue **${{ github.workflow }}**. \n\n 提交的散列为：_${{ github.sha }}_.”}'
